version: 2.1

jobs:
  download_and_upload:
    docker:
      - image: circleci/python:3.8  # You can choose an Ubuntu-based image, e.g., `cimg/base:stable`
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl nodejs npm
            npm install -g webtorrent-cli

      - run:
          name: Download torrent
          command: |
            mkdir -p ~/downloaded_files
            webtorrent download "magnet:?xt=urn:btih:86B445126B4BA01A726D5EC9484F1E4F0F0B7334&dn=Evil%20Lives%20Here%20The%20Killer%20Speaks%20S02E08%20She%20Was%20All%20Darkness%201080p%20AMZN%20WEB-DL%20DDP2%200%20H%20264-RAWR%5BEZTVx.to%5D.mkv%5Beztv%5D" --out ~/downloaded_files

      - run:
          name: Upload files to Filebin
          command: |
            BIN_NAME="fn5l2fc0lh3bplas" # Change this to your desired bin name
            find ~/downloaded_files -type f -print0 | while IFS= read -r -d '' file; do
              filename=$(basename "$file")
              echo "Uploading $filename..."
              curl -X POST --data-binary @"$file" "https://filebin.net/$BIN_NAME/$filename"
            done

workflows:
  version: 2
  build:
    jobs:
      - download_and_upload
